reg_keys_to_human = {
    "shutdownwithoutlogon": "Shutdown: Allow system to be shut down without having to log on",
    "cachedlogonscount": "Interactive logon: Number of previous logons to cache (in case domain controller is not available)",
    "restrictanonymous": "Network access: Do not allow anonymous enumeration of SAM accounts",
    "enableforcedlogoff": "Microsoft network server: Disconnect clients when logon hours expire",
    "enableplaintextpassword": "Microsoft network client: Send unencrypted password to third-party SMB servers",
    "autoadminlogon": "MSS: (AutoAdminLogon) Enable Automatic Logon (not recommended)",
    "addprinterdrivers": "Devices: Prevent users from installing printer drivers",
    "disablecad": "Interactive logon: Do not require CTRL+ALT+DEL",
    "scremoveoption": "Interactive logon: Smart card removal behavior",
    "enablesecuritysignature": "Microsoft network client: Digitally sign communications (if server agrees)",
    "sealsecurechannel": "Domain Member: Digitally encrypt secure channel data (when possible)",
    "signsecurechannel": "Domain Member: Digitally sign secure channel data (when possible)",
    "disablepasswordchange": "Domain Member: Disable Machine Account Password Changes",
    "passwordexpirywarning": "Interactive Logon: Prompt user to change password before expiration",
    "protectionmode": "System objects: Strengthen default permissions of internal system objects (e.g. Symbolic Links)",
    "autodisconnect": "Microsoft network server: Amount of idle time required before suspending session",
    "dontdisplaylastusername": "Interactive logon: Do not display last user name",
    "auditbaseobjects": "Audit: Audit the access of global system objects",
    "fullprivilegeauditing": "Audit: Audit the use of Backup and Restore privilege",
    "filteradministratortoken": "User Account Control: Admin Approval Mode for the Built-in Administrator account",
    "consentpromptbehavioradmin": "User Account Control: Behavior of the elevation prompt for administrators in Admin Approval Mode",
    "consentpromptbehavioruser": "User Account Control: Behavior of the elevation prompt for standard users",
    "enableinstallerdetection": "User Account Control: Detect application installations and prompt for elevation",
    "enablesecureuiapaths": "User Account Control: Only elevate UIAccess applications that are installed in secure locations",
    "enablelua": "User Account Control: Run all administrators in Admin Approval Mode",
    "promptonsecuredesktop": "User Account Control: Switch to the secure desktop when prompting for elevation",
    "enablevirtualization": "User Account Control: Virtualize file and registry write failures to per-user locations",
    "enableuiadesktoptoggle": "User Account Control: Allow UIAccess applications to prompt for elevation without using the secure desktop",
    "validateadmincodesignatures": "User Account Control: Only elevate executables that are signed and validated",
    "restrictanonymoussam": "Network access: Do not allow anonymous enumeration of SAM accounts",
    "machine": "Network access: Remotely accessible registry paths",
    "limitblankpassworduse": "Accounts: Limit local account use of blank passwords to console logon only",
    "maximumpasswordage": "Domain member: Maximum machine account password age",
    "requirestrongkey": "Domain Member: Require Strong (Windows 2000 or Later) Session Key",
    "disabledomaincreds": "Network access: Do not allow storage of passwords and credentials for network authentication",
    "everyoneincludesanonymous": "Network access: Let everyone permissions apply to anonymous users",
    "forceguest": "Network access: Sharing and security model for local accounts",
    "nolmhash": "Network security: Do not store LAN Manager hash value on next password change",
    "ldapclientintegrity": "Network security: LDAP client signing requirements",
    "ntlmminclientsec": "Network security: Minimum session security for NTLM SSP based (including secure RPC) clients",
    "enabled": "System cryptography: Use FIPS compliant algorithms for encryption, hashing, and signing",
    "obcaseinsensitive": "System objects: Require case insensitivity for non-Windows subsystems",
    "ntlmminserversec": "Network security: Minimum session security for NTLM SSP based (including secure RPC) servers",
    "enableicmpredirect": "MSS: (EnableICMPRedirect) Allow ICMP redirects to override OSPF generated routes",
    "disableautomaticrestartsignon": "Sign-in last interactive user automatically after a system-initiated restart",
    "optional": "System settings: Optional subsystems",
    "requiresignorseal": "Domain member: Digitally encrypt or sign secure channel data (always)",
    "requiresecuritysignature": "Microsoft network client: Digitally sign communications (always)",
    "smb1": "SMBv1 Server",
    "start": "SMBv1 client driver",
    "dependonservice": "SMBv1 client driver",
    "forceunlocklogon": "Interactive logon: Require Domain Controller Authentication to unlock workstation",
    "clearpagefileatshutdown": "Shutdown: Clear virtual memory pagefile",
    "undockwithoutlogon": "Devices: Allow undock without having to log on",
    "authenticodeenabled": "System settings: Use Certificate Rules on Windows Executables for Software Restriction Policies",
    "crashonauditfail": "Audit: Shut down system immediately if unable to log security audits",
    "nullsessionpipes": "Network access: Named pipes that can be accessed anonymously",
    "restrictnullsessaccess": "Network access: Restrict anonymous access to Named Pipes and Shares"
}
